services:
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: msn_server
      POSTGRES_PASSWORD: msn_server
      POSTGRES_DB: msn_server
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:7-alpine
    restart: always
    environment:
      REDIS_PASSWORD: msn_server
    command: sh -c 'redis-server --requirepass $$REDIS_PASSWORD'
    ports:
      - 127.0.0.1:6379:6379

volumes:
  db_data:
