services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: msn_server
      POSTGRES_PASSWORD: msn_server
      POSTGRES_DB: msn_server

volumes:
  db_data:
